In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
#!pip install --upgrade openpyxl (if we cannot read excel file then)

In [4]:
emp=pd.read_excel(r"C:\Users\HP\Downloads\Rawdata.xlsx")

In [5]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [6]:
id(emp)

1874504266288

In [7]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [8]:
emp.shape

(6, 6)

In [9]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [10]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [11]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [12]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [13]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [14]:
emp.isna()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [15]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [16]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [17]:
emp.dtypes

Name        object
Domain      object
Age         object
Location    object
Salary      object
Exp         object
dtype: object

In [18]:
emp.describe()

        Name         Domain       Age Location  Salary Exp
count      6              6         4        4       6   5
unique     6              6         4        4       6   5
top     Mike  Datascience#$  34 years   Mumbai  5^00#0  2+
freq       1              1         1        1       1   1

# Data Cleaning

In [19]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [20]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [21]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [25]:
emp['Name']=emp['Name'].str.replace(r'\W','',regex=True) #deletes the non word characters

In [26]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [27]:
emp

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [28]:
emp['Domain']=emp['Domain'].str.replace(r'\W','',regex=True)

In [29]:
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [30]:
emp['Location']=emp['Location'].str.replace(r'\W','',regex=True)

In [31]:
emp

    Name       Domain       Age   Location   Salary      Exp
0   Mike  Datascience  34 years     Mumbai   5^00#0       2+
1  Teddy      Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst       NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics       NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67-yr        NaN   30000-  5+ year
5    Kim          NLP      55yr      Delhi  6000^$0      10+

In [32]:
emp['Age']=emp['Age'].str.replace(r'\W','',regex=True)

In [33]:
emp

    Name       Domain      Age   Location   Salary      Exp
0   Mike  Datascience  34years     Mumbai   5^00#0       2+
1  Teddy      Testing     45yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst      NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics      NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics     67yr        NaN   30000-  5+ year
5    Kim          NLP     55yr      Delhi  6000^$0      10+

In [34]:
emp['Age']=emp['Age'].str.extract('(\d+)')

In [35]:
emp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [36]:
emp['Salary']=emp['Salary'].str.replace(r'\W','',regex=True)

In [37]:
emp

    Name       Domain  Age   Location Salary      Exp
0   Mike  Datascience   34     Mumbai   5000       2+
1  Teddy      Testing   45  Bangalore  10000       <3
2   Umar  Dataanalyst  NaN        NaN  15000   4> yrs
3   Jane    Analytics  NaN   Hyderbad  20000      NaN
4  Uttam   Statistics   67        NaN  30000  5+ year
5    Kim          NLP   55      Delhi  60000      10+

In [38]:
emp['Exp']=emp['Exp'].str.replace(r'\W','',regex=True)

In [39]:
emp

    Name       Domain  Age   Location Salary    Exp
0   Mike  Datascience   34     Mumbai   5000      2
1  Teddy      Testing   45  Bangalore  10000      3
2   Umar  Dataanalyst  NaN        NaN  15000   4yrs
3   Jane    Analytics  NaN   Hyderbad  20000    NaN
4  Uttam   Statistics   67        NaN  30000  5year
5    Kim          NLP   55      Delhi  60000     10

In [40]:
emp['Exp']=emp['Exp'].str.extract('(\d+)')

In [41]:
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [42]:
clean_data=emp.copy()

In [43]:
clean_data

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [44]:
clean_data.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

## EDA Technique: 1st technique -- Missing value treatment

In [45]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [46]:
import numpy as np

In [47]:
clean_data['Age']=clean_data['Age'].fillna(np.mean(pd.to_numeric(clean_data['Age'])))

In [48]:
clean_data['Age']

0       34
1       45
2    50.25
3    50.25
4       67
5       55
Name: Age, dtype: object

In [49]:
clean_data['Exp']=clean_data['Exp'].fillna(np.mean(pd.to_numeric(clean_data['Exp'])))

In [50]:
clean_data

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25        NaN  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67        NaN  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [51]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [52]:
clean_data['Location']

0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

In [53]:
clean_data['Location']=clean_data['Location'].fillna(np.mode(pd.to_numeric(clean_data['Location'])))

AttributeError: module 'numpy' has no attribute 'mode'

In [54]:
clean_data['Location']=clean_data['Location'].fillna(clean_data['Location'].mode()[0])

In [55]:
clean_data['Location']

0       Mumbai
1    Bangalore
2    Bangalore
3     Hyderbad
4    Bangalore
5        Delhi
Name: Location, dtype: object

In [56]:
clean_data

    Name       Domain    Age   Location Salary  Exp
0   Mike  Datascience     34     Mumbai   5000    2
1  Teddy      Testing     45  Bangalore  10000    3
2   Umar  Dataanalyst  50.25  Bangalore  15000    4
3   Jane    Analytics  50.25   Hyderbad  20000  4.8
4  Uttam   Statistics     67  Bangalore  30000    5
5    Kim          NLP     55      Delhi  60000   10

In [57]:
id(clean_data)

1874503654416

In [58]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       6 non-null      object
 3   Location  6 non-null      object
 4   Salary    6 non-null      object
 5   Exp       6 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [59]:
clean_data.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [60]:
clean_data['Age']=clean_data['Age'].astype(int)
clean_data['Exp']=clean_data['Exp'].astype(int)
clean_data['Salary']=clean_data['Salary'].astype(int)

clean_data['Name']=clean_data['Name'].astype('category')
clean_data['Domain']=clean_data['Domain'].astype('category')
clean_data['Location']=clean_data['Location'].astype('category')

In [61]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      category
 1   Domain    6 non-null      category
 2   Age       6 non-null      int64
 3   Location  6 non-null      category
 4   Salary    6 non-null      int64
 5   Exp       6 non-null      int64
dtypes: category(3), int64(3)
memory usage: 938.0 bytes

In [62]:
type(clean_data)

pandas.core.frame.DataFrame

In [63]:
clean_data

    Name       Domain  Age   Location  Salary  Exp
0   Mike  Datascience   34     Mumbai    5000    2
1  Teddy      Testing   45  Bangalore   10000    3
2   Umar  Dataanalyst   50  Bangalore   15000    4
3   Jane    Analytics   50   Hyderbad   20000    4
4  Uttam   Statistics   67  Bangalore   30000    5
5    Kim          NLP   55      Delhi   60000   10

In [64]:
clean_data.to_csv('clean_data.csv')

In [65]:
import os

In [66]:
os.getcwd()

'C:\\Users\\HP'